### ISSUE TITLE
Website Feedback

### ISSUE THREAD

**Issue by mreid1130** [lnbcoding/lnbcoding.github.io#2]
Hey Leonard,

It looks like your website has a really nice frame setup for future, I really like the layout of the toolbar as well as the social media connection bar in the top right corner. I had placed mine in the bottom right corner and had some issues, so I may make an adjustment after seeing the look of your site!

The one thing I noticed when navigating your site was that the toolbar was not consistent on the blog page (the blog button was removed). That kind of threw me off when I first was looking through your site and tried quickly clinking through the toolbar, but I understand why you wouldn't need a blog button on the blog page, but it felt a little clunky to see the text buttons all slide over.

Really nice looking site, and I love the use of images on all the pages. Definitely has a lot of flair and maintains a simple layout.

Hope that helps! Have a good week 3!

**Comment by lnbcoding** [comment]
Hey Mark, 

Thanks for the feedback. I noticed the links changing too when I was on the testing challenge. Will need to fix them or create a separate blog index page. 

Regards
