### ISSUE TITLE
elsif Ruby ... else if (Javascript)

### ISSUE THREAD

**Issue by planarian** [lnbcoding/lnbcoding.github.io#4]
Hi Leonard,

I really sympathize with your struggles with JavaScript. The interpreter offers so little feedback you can easily spend hours trying to troubleshoot relatively simple code. As I posted on the forum earlier this week, there's are a couple Sublime plugins that will point out problems in your JavaScript as you type. I find it _enormously_ helpful. You might want to consider checking out JSHint (first install Package Control if you don't already have it. See the Tuts Sublime tutorial for more info).

Regards,

Jay Davis

**Comment by lnbcoding** [comment]
This is a belated thanks but the JSHint is very userful

**Comment by planarian** [comment]
Glad to hear it!
